export const PAGE_TO_JSON_KEY = {
    '/kite/freelancer/school-support': 'SchoolSupportPage',
    '/kite/freelancer/travel-services': 'TravelServicesPage',
    '/kite/freelancer/consulting': 'ConsultingPage',
    '/kite/courses/theory': 'TheoryPage',
    '/kite/courses/starting': 'StartingPage',
    '/kite/courses/advanced': 'AdvancedPage',
    '/engineer/process-engineering/process-control': 'ProcessControlPage',
    '/engineer/process-engineering/process-optimization': 'ProcessOptimizationPage',
    '/engineer/process-engineering/change-management': 'ChangeManagementPage',
    '/engineer/process-engineering/monitoring': 'MonitoringPage',
    '/engineer/process-development/creativity': 'CreativityPage',
    '/engineer/process-development/process-design': 'ProcessDesignPage',
    '/engineer/process-development/simulation-prototyping': 'SimulationPrototypingPage',
    '/engineer/process-development/equipment-roadmap': 'EquipmentRoadmapPage',
    '/engineer/software-development/custom-solutions': 'CustomSolutionsPage',
    '/engineer/software-development/database-management': 'DatabaseManagementPage',
    '/engineer/software-development/workflow-automation': 'WorkflowAutomationPage',
    '/engineer/software-development/web-development': 'WebDevelopmentPage',
    '/engineer/project-management/project-setup': 'ProjectSetupPage',
    '/engineer/project-management/timeline-management': 'TimelineManagementPage',
    '/engineer/project-management/deviation-management': 'DeviationManagementPage',
    '/engineer/project-management/documentation': 'DocumentationPage',
    '/engineer/technical-consulting/process-assessment': 'ProcessAssessmentPage',
    '/engineer/technical-consulting/technical-research': 'TechnicalResearchPage',
    '/engineer/technical-consulting/training-knowledge-transfer': 'TrainingKnowledgeTransferPage',
    '/engineer/technical-consulting/competitor-analysis': 'CompetitorAnalysisPage',
    '/about': 'AboutPage',
    '/contact': 'ContactPage',
    '/kite': 'KitePage',
    '/engineer': 'EngineerPage'
} as const;

export const PAGE_TO_NAV_KEY = {
    'SchoolSupportPage': 'schoolSupport',
    'TravelServicesPage': 'travelServices',
    'ConsultingPage': 'consulting',
    'TheoryPage': 'theory',
    'StartingPage': 'starting',
    'AdvancedPage': 'advanced',
    'ProcessControlPage': 'processControl',
    'ProcessOptimizationPage': 'processOptimization',
    'ChangeManagementPage': 'changeManagement',
    'MonitoringPage': 'monitoring',
    'CreativityPage': 'creativity',
    'ProcessDesignPage': 'processDesign',
    'SimulationPrototypingPage': 'simulationPrototyping',
    'EquipmentRoadmapPage': 'equipmentRoadmap',
    'CustomSolutionsPage': 'customSolutions',
    'DatabaseManagementPage': 'databaseManagement',
    'WorkflowAutomationPage': 'workflowAutomation',
    'WebDevelopmentPage': 'webDevelopment',
    'ProjectSetupPage': 'projectSetup',
    'TimelineManagementPage': 'timelineManagement',
    'DeviationManagementPage': 'deviationManagement',
    'DocumentationPage': 'documentation',
    'ProcessAssessmentPage': 'processAssessment',
    'TechnicalResearchPage': 'technicalResearch',
    'TrainingKnowledgeTransferPage': 'trainingKnowledgeTransfer',
    'CompetitorAnalysisPage': 'competitorAnalysis',
    'AboutPage': 'about',
    'ContactPage': 'contact',
    'KitePage': 'kite',
    'EngineerPage': 'engineer'
} as const;

export type PagePath = keyof typeof PAGE_TO_JSON_KEY;
export type JsonKey = keyof typeof PAGE_TO_NAV_KEY;
export type NavKey = typeof PAGE_TO_NAV_KEY[JsonKey];