import { types } from "util";

export const STOP_WORDS: string[] = [
  // English stop words
  'll', 've', 'a', 'able', 'about', 'above', 'abst', 'accordance', 'according', 'accordingly', 
  'across', 'act', 'actually', 'added', 'adj', 'affected', 'affecting', 'affects', 'after', 
  'afterwards', 'again', 'against', 'ah', 'all', 'almost', 'alone', 'along', 'already', 'also', 
  'although', 'always', 'am', 'among', 'amongst', 'an', 'and', 'announce', 'another', 'any', 
  'anybody', 'anyhow', 'anymore', 'anyone', 'anything', 'anyway', 'anyways', 'anywhere', 
  'apparently', 'approximately', 'are', 'aren', 'arent', 'arise', 'around', 'as', 'aside', 
  'ask', 'asking', 'at', 'auth', 'available', 'away', 'awfully', 'b', 'back', 'be', 'became', 
  'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'begin', 
  'beginning', 'beginnings', 'begins', 'behind', 'being', 'believe', 'below', 'beside', 
  'besides', 'between', 'beyond', 'biol', 'both', 'brief', 'briefly', 'but', 'by', 'c', 'ca', 
  'came', 'can', 'can\'t', 'cannot', 'cause', 'causes', 'certain', 'certainly', 'co', 'com', 
  'come', 'comes', 'contain', 'containing', 'contains', 'could', 'couldnt', 'd', 'date', 'did', 
  'didn\'t', 'different', 'do', 'does', 'doesn\'t', 'doing', 'don\'t', 'done', 'down', 
  'downwards', 'due', 'during', 'e', 'each', 'ed', 'edu', 'effect', 'eg', 'eight', 'eighty', 
  'either', 'else', 'elsewhere', 'end', 'ending', 'enough', 'especially', 'et', 'et-al', 'etc', 
  'even', 'ever', 'every', 'everybody', 'everyone', 'everything', 'everywhere', 'ex', 'except', 
  'f', 'far', 'few', 'ff', 'fifth', 'first', 'five', 'fix', 'followed', 'following', 'follows', 
  'for', 'former', 'formerly', 'forth', 'found', 'four', 'from', 'further', 'furthermore', 'g', 
  'gave', 'get', 'gets', 'getting', 'give', 'given', 'gives', 'giving', 'go', 'goes', 'gone', 
  'got', 'gotten', 'h', 'had', 'happens', 'hardly', 'has', 'hasn\'t', 'have', 'haven\'t', 
  'having', 'he', 'hed', 'hence', 'her', 'here', 'hereafter', 'hereby', 'herein', 'heres', 
  'hereupon', 'hers', 'herself', 'hes', 'hi', 'hid', 'him', 'himself', 'his', 'hither', 'home', 
  'how', 'howbeit', 'however', 'hundred', 'i', 'i\'ll', 'i\'ve', 'id', 'ie', 'if', 'im', 
  'immediate', 'immediately', 'importance', 'important', 'in', 'inc', 'indeed', 'index', 
  'information', 'instead', 'into', 'invention', 'inward', 'is', 'isn\'t', 'it', 'it\'ll', 
  'itd', 'its', 'itself', 'j', 'just', 'k', 'keep', 'keeps', 'kept', 'kg', 'km', 'know', 
  'known', 'knows', 'l', 'largely', 'last', 'lately', 'later', 'latter', 'latterly', 'least', 
  'less', 'lest', 'let', 'lets', 'like', 'liked', 'likely', 'line', 'little', 'look', 'looking', 
  'looks', 'ltd', 'm', 'made', 'mainly', 'make', 'makes', 'many', 'may', 'maybe', 'me', 'mean', 
  'means', 'meantime', 'meanwhile', 'merely', 'mg', 'might', 'million', 'miss', 'ml', 'more', 
  'moreover', 'most', 'mostly', 'mr', 'mrs', 'much', 'mug', 'must', 'my', 'myself', 'n', 'na', 
  'name', 'namely', 'nay', 'nd', 'near', 'nearly', 'necessarily', 'necessary', 'need', 'needs', 
  'neither', 'never', 'nevertheless', 'new', 'next', 'nine', 'ninety', 'no', 'nobody', 'non', 
  'none', 'nonetheless', 'noone', 'nor', 'normally', 'nos', 'not', 'noted', 'nothing', 'now', 
  'nowhere', 'o', 'obtain', 'obtained', 'obviously', 'of', 'off', 'often', 'oh', 'ok', 'okay', 
  'old', 'omitted', 'on', 'once', 'one', 'ones', 'only', 'onto', 'or', 'ord', 'other', 'others', 
  'otherwise', 'ought', 'our', 'ours', 'ourselves', 'out', 'outside', 'over', 'overall', 'owing', 
  'own', 'p', 'page', 'pages', 'part', 'particular', 'particularly', 'past', 'per', 'perhaps', 
  'placed', 'please', 'plus', 'poorly', 'possible', 'possibly', 'potentially', 'pp', 
  'predominantly', 'present', 'previously', 'primarily', 'probably', 'promptly', 'proud', 
  'provides', 'put', 'q', 'que', 'quickly', 'quite', 'qv', 'r', 'ran', 'rather', 'rd', 're', 
  'readily', 'really', 'recent', 'recently', 'ref', 'refs', 'regarding', 'regardless', 'regards', 
  'related', 'relatively', 'research', 'respectively', 'resulted', 'resulting', 'results', 
  'right', 'run', 's', 'said', 'same', 'saw', 'say', 'saying', 'says', 'sec', 'section', 'see', 
  'seeing', 'seem', 'seemed', 'seeming', 'seems', 'seen', 'self', 'selves', 'sent', 'seven', 
  'several', 'shall', 'she', 'she\'ll', 'shed', 'shes', 'should', 'shouldn\'t', 'show', 
  'showed', 'shown', 'showns', 'shows', 'significant', 'significantly', 'similar', 'similarly', 
  'since', 'six', 'slightly', 'so', 'some', 'somebody', 'somehow', 'someone', 'somethan', 
  'something', 'sometime', 'sometimes', 'somewhat', 'somewhere', 'soon', 'sorry', 'specifically', 
  'specified', 'specify', 'specifying', 'still', 'stop', 'strongly', 'sub', 'substantially', 
  'successfully', 'such', 'sufficiently', 'suggest', 'sup', 'sure', 't', 'take', 'taken', 
  'taking', 'tell', 'tends', 'th', 'than', 'thank', 'thanks', 'thanx', 'that', 'that\'ll', 
  'that\'ve', 'thats', 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'thence', 
  'there', 'there\'ll', 'there\'ve', 'thereafter', 'thereby', 'thered', 'therefore', 'therein', 
  'thereof', 'therere', 'theres', 'thereto', 'thereupon', 'these', 'they', 'they\'ll', 
  'they\'ve', 'theyd', 'theyre', 'think', 'this', 'those', 'thou', 'though', 'thoughh', 
  'thousand', 'throug', 'through', 'throughout', 'thru', 'thus', 'til', 'tip', 'to', 'together', 
  'too', 'took', 'toward', 'towards', 'tried', 'tries', 'truly', 'try', 'trying', 'ts', 'twice', 
  'two', 'u', 'un', 'under', 'unfortunately', 'unless', 'unlike', 'unlikely', 'until', 'unto', 
  'up', 'upon', 'ups', 'us', 'use', 'used', 'useful', 'usefully', 'usefulness', 'uses', 'using', 
  'usually', 'v', 'value', 'various', 'very', 'via', 'viz', 'vol', 'vols', 'vs', 'w', 'want', 
  'wants', 'was', 'wasnt', 'way', 'we', 'we\'ll', 'we\'ve', 'wed', 'welcome', 'went', 'were', 
  'werent', 'what', 'what\'ll', 'whatever', 'whats', 'when', 'whence', 'whenever', 'where', 
  'whereafter', 'whereas', 'whereby', 'wherein', 'wheres', 'whereupon', 'wherever', 'whether', 
  'which', 'while', 'whim', 'whither', 'who', 'who\'ll', 'whod', 'whoever', 'whole', 'whom', 
  'whomever', 'whos', 'whose', 'why', 'widely', 'willing', 'wish', 'with', 'within', 'without', 
  'wont', 'words', 'world', 'would', 'wouldnt', 'www', 'x', 'y', 'yes', 'yet', 'you', 'you\'ll', 
  'you\'ve', 'youd', 'your', 'youre', 'yours', 'yourself', 'yourselves', 'z', 'zero',

  // German stop words
  'aber', 'als', 'am', 'an', 'auch', 'auf', 'aus', 'bei', 'bin', 'bis', 'bist', 'da', 'dadurch', 
  'daher', 'darum', 'das', 'dass', 'daß', 'dein', 'deine', 'dem', 'den', 'der', 'des', 'deshalb', 
  'dessen', 'die', 'dies', 'dieser', 'dieses', 'doch', 'dort', 'du', 'durch', 'ein', 'eine', 
  'einem', 'einen', 'einer', 'eines', 'er', 'es', 'euer', 'eure', 'für', 'hatte', 'hatten', 
  'hattest', 'hattet', 'hier', 'hinter', 'ich', 'ihr', 'ihre', 'im', 'in', 'ist', 'ja', 'jede', 
  'jedem', 'jeden', 'jeder', 'jedes', 'jener', 'jenes', 'jetzt', 'kann', 'kannst', 'können', 
  'könnt', 'machen', 'mein', 'meine', 'mit', 'musst', 'muss', 'musst', 'müssen', 'müsst', 'nach', 
  'nachdem', 'nein', 'nicht', 'nun', 'oder', 'seid', 'sein', 'seine', 'sich', 'sie', 'sind', 
  'soll', 'sollen', 'sollst', 'sollt', 'sonst', 'soweit', 'sowie', 'und', 'unser', 'unsere', 
  'unter', 'vom', 'von', 'vor', 'wann', 'warum', 'was', 'weiter', 'weitere', 'wenn', 'wer', 
  'werde', 'werden', 'werdet', 'weshalb', 'wie', 'wieder', 'wieso', 'wir', 'wird', 'wirst', 
  'wo', 'woher', 'wohin', 'zu', 'zum', 'zur', 'über',

  // Portuguese stop words
  'acerca', 'agora', 'algmas', 'alguns', 'ali', 'ambos', 'antes', 'apontar', 'aquela', 'aquelas', 
  'aquele', 'aqueles', 'aqui', 'atrás', 'bem', 'bom', 'cada', 'caminho', 'cima', 'com', 'como', 
  'comprido', 'conhecido', 'corrente', 'das', 'debaixo', 'dentro', 'desde', 'desligado', 'deve', 
  'devem', 'deverá', 'direita', 'diz', 'dizer', 'dois', 'dos', 'e', 'ela', 'ele', 'eles', 'em', 
  'enquanto', 'então', 'estado', 'estar', 'estará', 'este', 'estes', 'esteve', 'estive', 
  'estivemos', 'estiveram', 'está', 'estão', 'eu', 'fará', 'faz', 'fazer', 'fazia', 'fez', 'fim', 
  'foi', 'fora', 'horas', 'iniciar', 'inicio', 'ir', 'irá', 'ista', 'iste', 'isto', 'ligado', 
  'maioria', 'maiorias', 'mais', 'mas', 'mesmo', 'meu', 'muito', 'muitos', 'nome', 'nosso', 
  'novo', 'não', 'nós', 'o', 'onde', 'os', 'ou', 'outro', 'para', 'parte', 'pegar', 'pelo', 
  'pessoas', 'pode', 'poderá', 'podia', 'por', 'porque', 'povo', 'promeiro', 'qual', 'qualquer', 
  'quando', 'quem', 'quieto', 'quê', 'saber', 'sem', 'ser', 'seu', 'somente', 'são', 'tal', 
  'também', 'tem', 'tempo', 'tenho', 'tentar', 'tentaram', 'tente', 'tentei', 'teu', 'teve', 
  'tipo', 'tive', 'todos', 'trabalhar', 'trabalho', 'tu', 'têm', 'um', 'uma', 'umas', 'uns', 
  'usa', 'usar', 'valor', 'veja', 'ver', 'verdade', 'verdadeiro', 'você', 'é', 'último'
];