on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  delete-package-versions:
    name: Rolling deletion of old images
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.CLEANUP_TOKEN }}
          image-names: "*"
          cut-off: 1d
          image-tags: "!latest"
          keep-n-most-recent: 5
