on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete-package-versions:
    name: Delete untagged package versions
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.CLEANUP_TOKEN }}
          image-names: "*"
          tag-selection: untagged
          image-tags: "!*latest*"
          cut-off: 1d
