name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Semantic Versioning"]
    types:
      - completed
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean previous build
        run: rm -rf .next

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Get the run_id of the most recent run workflow
        id: get_run_id
        run: |
          # Use the GitHub API to get the latest run_id of the first workflow
          run_id=$(curl -s -H "Authorization: token ${{ secrets.GH_PACKAGE_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/release.yml/runs" | \
            jq -r '.workflow_runs[0].id')
          echo "run_id=$run_id" >> $GITHUB_OUTPUT
          echo "Current run_id: $run_id"

      - name: Clone external action repository
        run: |
          git clone https://github.com/kamilchodola/wait-for-workflow-action.git /tmp/wait-for-workflow-action
          ls -la /tmp/wait-for-workflow-action

      - name: Make the script executable
        run: |
          if [ -f /tmp/wait-for-workflow-action/scripts/wait-for-workflow.sh ]; then
            chmod +x /tmp/wait-for-workflow-action/scripts/wait-for-workflow.sh
          else
            echo "Error: /tmp/wait-for-workflow-action/scripts/wait-for-workflow.sh does not exist."
            exit 1
          fi

      - name: Wait for Workflow Action
        run: /tmp/wait-for-workflow-action/scripts/wait-for-workflow.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
          WORKFLOW_ID: "build-and-push.yml"
          RUN_ID: ${{ steps.get_run_id.outputs.run_id }}
          MAX_WAIT_MINUTES: "3"
          INTERVAL: "5"
          TIMEOUT: "10"
          ORG_NAME: "dasteff91"
          REPO_NAME: "website_kite-engineer"
          REF: "${{ github.ref }}"

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dasteff91/website_kite-engineer
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_CLIENTVAR=clientvar

  deploy:
    name: Deploy to server
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo ${{ secrets.GH_PACKAGE_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/dasteff91/website_kite-engineer:${{ github.ref_name }}
            docker stop www-dev.kite-engineer.de || true
            docker rm www-dev.kite-engineer.de || true
            docker run -d --name "www-dev.kite-engineer.de" -p 3001:3000 --restart unless-stopped ghcr.io/dasteff91/website_kite-engineer:${{ github.ref_name }}
