# The name of the action displayed in GitHub
name: Build and Push Docker Image

# What triggers the action?
# When something gets pushed into the dev branch
on:
  push:
    branches:
      - dev
    # Changes in these files are ignored
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".next/**"
      - "node_modules/**"
      - ".env*"
      - "*ignore*"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/dasteff91/website_kite-engineer:latest .

      - name: Save Docker image
        run: docker save ghcr.io/dasteff91/website_kite-engineer:latest -o website_kite-engineer.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: website_kite-engineer
          path: website_kite-engineer.tar

  push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: website_kite-engineer

      - name: Load Docker image
        run: docker load -i website_kite-engineer.tar

      - name: Build and push Docker image for linux/amd64
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ghcr.io/dasteff91/website_kite-engineer:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_CLIENTVAR=clientvar

  deploy:
    name: Deploy to server
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/dasteff91/website_kite-engineer:latest
            docker stop www-dev.kite-engineer.de || true
            docker rm www-dev.kite-engineer.de || true
            docker run -d --name "www-dev.kite-engineer.de" -p 3001:3000 ghcr.io/dasteff91/website_kite-engineer:latest --restart unless-stopped
