name: Notify on dev push

on:
  push:
    branches:
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Just a success message
        run: echo "Pushed to dev branch – success!"
