name: Semantic Versioning
on:
  push:
    branches:
      - dev
      - development

jobs:
  versioning:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMVERSIONING }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm ci

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMVERSIONING }}

      - name: Verify semantic-release tag
        run: |
          echo "Latest tag: $(git describe --tags --abbrev=0)"
          echo "Tag SHA:    $(git rev-list -n 1 v1.14.8)"
          echo "HEAD SHA:   $(git rev-parse HEAD)"
          git log -1 --oneline
